### ISSUE TITLE
Implement easy metadata flag on CLI

### ISSUE THREAD

**Issue by gmelodie** [filecoin-project/index-provider#209] opened 2022-04-05 17:38 UTC
Currently when specifying `--metadata` on the CLI you have to manually marshall and base64 encode the `bitswap{}` or graphsync struct and then pass it to the flag. It would be nice to simply have a `--protocol` flag that you can specify `--protocol graphsync` (for bitswap you make it the default value). Maybe the `proto` flag already does that, not sure, but if that's the case maybe we could change it to `--proto [bitswap | graphsync]` instead of using cryptic numeric values.

**Comment by masih** [comment] 2022-04-05 19:31
Duplicate of https://github.com/filecoin-project/index-provider/issues/199. Closing. Please re-open if you think this is different.

**Closed by masih** 2022-04-05 19:31 UTC
